// Room context

export const roomContextActions = {
    SET_ROOM: 'SET-ROOM',
    SET_TRIVIA: 'SET-TRIVIA',
    SET_PARTICIPANT: 'SET_PARTICIPANT',
    SET_INVALID_ROOM: 'SET_INVALID_ROOM',
    SET_TRIVIA_STARTED: 'SET_TRIVIA_STARTED',
    UPDATE_SCORE: 'UPDATE_SCORE',
}
